name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check if build succeeds
      run: npm run build
      
    - name: Run critical API format tests
      run: npm run test:api-format
      
    - name: Run type checking
      run: npm run typecheck
      
    - name: Comment PR with test results
      uses: actions/github-script@v7
      if: always()
      with:
        script: |
          const { context } = require('@actions/github');
          const jobStatus = '${{ job.status }}';
          
          const comment = jobStatus === 'success' 
            ? '✅ All checks passed! The API format tests confirm that ElevenLabs integration will work correctly.'
            : '❌ Some checks failed. Please review the failing tests, especially the API format tests.';
            
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });

  compatibility:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Test Node.js ${{ matrix.node-version }} compatibility
      run: |
        npm run build
        npm run test:unit
        
    - name: Verify CLI functionality
      run: |
        node dist/cli.js --help
        node dist/cli.js config show
        node dist/cli.js providers